### ISSUE TITLE
The following problem occurs when running ./rb_generate_flagging B0.mesh B0.flag. How to solve it?

### ISSUE THREAD

**Issue by xupeiwust** [fprotais/robustPolycube#1]
C:/fprotais/softwares/graphite/build/Windows/bin/Release/graphite.exe: not found

**Comment by fprotais** [comment]
Hi @xupeiwust, 
Two possibilities, they both resolve around changing the 
`#define DEBUG_GRAPHITE_PATH `
at the beginning of the code in bin/generate_flagging.cpp, line 6. 
You can replace `"C:/fprotais/softwares/graphite/build/Windows/bin/Release/graphite.exe"` by: 
1. `""` if you don't want any debug output.
2. your own path after install graphite yourself: https://github.com/BrunoLevy/GraphiteThree ; the code will output the various steps it worked with, and can be a nice way to follow the progress of the algorithm. 

You'll need to do the operation for each file in the bin directories you want to run.
