### ISSUE TITLE
not able to run ./rb_generate_flagging fails nor ./rb_generate_quantization

### ISSUE THREAD

**Issue by otaolafranc** [fprotais/robustPolycube#3]
hello,
I just compiled the git. but there are some dependencies that do not come with it? when I run `./rb_generate_flagging ../mesh/B0.mesh B0.flag `
I get the error of a hardcoded path? `sh: 1: C:/fprotais/softwares/graphite/build/Windows/bin/Release/graphite.exe: not found
` on the other side, (I imagine that if the flag generation does not work the generate_quantization will not either in any case 
```
./rb_generate_quantization ../mesh/B0.mesh 1. B0_hexmesh.mesh
sh: 1: -h: not found
sh: 1: --version: not found
sh: 1: cplex: not found
sh: 1: -h: not found
No MILP solver found, will run default algorithm...
Failed to open B0_hexmesh.mesh
Meshes given: ../mesh/B0.mesh
 and B0_hexmesh.mesh
are incompatible, we abort.
```

also in the readme file there is an error about this command, right now it is:
`./rb_generate_quantization B0.mesh 1. B0_hexmesh.mesh` when it should be `./rb_generate_quantization ../mesh/B0.mesh 1. B0_hexmesh.mesh`

regards,
franco

**Comment by fprotais** [comment]
Hey there Franco, 
The error is misleading, the code succeeded actually!
Do you have GraphiteThree installed on your machine? (https://github.com/BrunoLevy/GraphiteThree) If so, you can use it to visualize my outputs (that can be interesting if you want to have a look at the inner workings). For that, you can modify the cmake call to be: 
``` 
cmake -DCMAKE_BUILD_TYPE=Release -DDEBUG_GRAPHITE_PATH=graphite ..
``` 
with graphite being you path to graphite executable (that can simply be graphite if you set the right env variable / sym link). I'll update the readme with that. 

If you don't care about debug info, you can still check if the executable created the required output. It should be the case, otherwise it is indeed a problem :) 

About robustness: you can run into "flaggings" which are incompatible with hexmeshes, in which case the code will fail, and not always in a predictable way. Debug output can help to diagnose that.

**Comment by otaolafranc** [comment]
hi françois,
sorry, but I am not sure what you mean by 'the code succeded actually' if I have a look at the directory there is no B0_hexmesh.mesh when I run:
```
./rb_generate_quantization ../mesh/B0.mesh 1. B0_hexmesh.mesh

sh: 1: -h: not found
sh: 1: --version: not found
sh: 1: cplex: not found
sh: 1: -h: not found
No MILP solver found, will run default algorithm...
Failed to open B0_hexmesh.mesh
Meshes given: ../mesh/B0.mesh
 and B0_hexmesh.mesh
are incompatible, we abort.

```

**Comment by fprotais** [comment]
Yes right, there a typo in the README.md. 
To run everything, the executable name should be `rb_fromscratch`. I'll correct that.

**Comment by otaolafranc** [comment]
thanks! my bad, i did not see that there was the typo. any doc/recommendation to check more about learning how to use it more than the default settings? maybe your thesis?

**Comment by fprotais** [comment]
I would say the README is the more up to date information. The paper does contextualize the code and what are its main contributions. My thesis can help, but will mostly repeat what the paper says, but in French. Here is me contextualizing  the thing in french: https://youtu.be/Xtegca1n6qE?si=I_U3qJvIa1A7kgDs

Note that it is research code, and while it can shine on certain models, it will drastically fail when the flagging is wrong. You can find paper such as Evocube (https://github.com/LIHPC-Computational-Geometry/evocube)  that made great use of this code by sending it difficult flaggings.

For a good flagging, the code should be able to handle any size of mesh you ask it (even 0! It will produce very coarse meshes). On that last point, you may need to plug in a MILP solver to get the best results. If you get to that point, and would like to have a lot of high quality coarse meshes, you can reach-out again and I can improve the README to include that.  

So all in all, if you want to do further research, I can spend some time explaining problems with the code and how to go around them. If you just want to generate meshes for an application, the code may not always fit your needs, but I will not be able to do much about it (the limitations are there for a reason, I failed to fixed them in the first place!) But I can help troubleshoot errors. The first step would be to have a look at the flagging through debug and see if somethings wrong.  Improvement may come in the future, but not immediately.

**Comment by otaolafranc** [comment]
perfect tomorrow I will have a look at it. I am not so far in research in meshing, but I am working in integrating the mesher with a complete workflow from a CAD model, using salome-platform which has a CAD and meshing kernel and uses python. the most I could offer to collaborate with the code, would be automatic flagging (not the ones used in polycube but for features) of nodes in regards to features of the CAD model, better surface meshing control etc. if this king of things could be added to help the code 'respect' the features, or even project them back to the real CAD geometry. eg. -> extract flags of features (vertex, edges & surfaces of CAD model) identify them, ->after meshing with polycube -> relie back the generated mesh with the CAD model to better projection and feature respect with that I can help  (if it is something that could be interesting for you to add to the pipeline of the algorithm)

**Comment by fprotais** [comment]
I know that Christophe Bourcier & Sebastien Mestrallet from CEA worked with this code and Salome. I don't know how much they customized the interface between the two. 

About CAD: introducing it into my process could be tricky, as my tools relies on degree of freedom the CAD may remove. But generating the flagging with CAD in mind could only be an improvement to what I have here currently. 

Some minor note: due to its dependencies, the code has a very restrictive license. It is alright for academic usages, but will be limiting for large deployments.

**Comment by otaolafranc** [comment]
Oh, did not notice about the license I thought that it was a LGPL 3! i integrated using python to salome, specially now that there is meshio on it. I imagine that christophe, did not added to salome directly for the license incopatibilities in any case I havent heard anything in the forum I imagine that it stayed as internal tests. what I thought from my side was more like, creating a pipeline between calls to salome and robustPolycube to increase its capabilities, if you are interested with this, I could help and leave it as an external script that could be used to call respective salome and robustPolycube calls and communication to get the best possible result. if it is something you could be interested on, you can count with me.

**Comment by fprotais** [comment]
While I am interested in my code being used, I currently don't have the engineering time to get rid of difficult licenses and improve bindings capabilities to make something reliably usable for people. I am currently in a new position, and while I may have time to allocate to improving the thing, not enough for a whole make-over. I will be there for small issue though, don't hesitate to create new issues. 

About getting the best of robustPolycube: first user must have an intuition about what will make a polycube work, there might be some presentations that help on that. And then the most important part is the flagging. The one here is really naive, and will fail on even simple geometry. A way to visualize and modify it through Salome would be the best. 

Regarding the License, what I would recommend is to create a new repo where you make your scripts available under AGPL license. This way, academic people interested may be able to play with it, with the a clear distinction that it cannot be used for commercial applications. If there is significant interest, I will allocate the time to improve it (or find people to do it), and we can figure out improvements to the current licensing (I may need a tetmesher though, maybe Salome has that?). 

BTW: if this code fail, I have a back-up one that is strangely robust (for non 0. scale coarse mesh) : 
https://github.com/fprotais/polycube_withHexEx
It can be optionally plug it after generating a flagging. It will not do post-processing. It is made to behave the same, so with the same license problems :)

**Comment by otaolafranc** [comment]
> A way to visualize and modify it through Salome would be the best.

no problem, easy-peasy importing the original flags, with coloring and be able to modify them by clicking and a small function to export the new flags (if you have an input in the colors I would appreciate so I can hardcode the colors (y))
![image](https://github.com/user-attachments/assets/76238d6c-2565-4575-94de-bd1ec7ecfa53)

> I would recommend is to create a new repo where you make your scripts available under AGPL license.

my main issue with this is put it in place.... I find quite difficult to work with github, I need to take my time to learn how to use it (github).

>I may need a tetmesher though, maybe Salome has that?

yes, salome have different tetmeshers, NETGEN (quite old version sadly, still waiting them to update it to a newer one) and also GMSH. the pipeline that I did was all automatic from select CAD (run my script)-> tri/tetra mesh -> export in mesh format -> robustPolycube -> import hexa mesh to salome

**Comment by fprotais** [comment]
color are usually coded as blue for X, white for Y and red for Z. But then it is a bit hard to distinguish +X from -X. I was using different shades of the colors (but for white?). I think it is good to have similar colors for the same dimension,                         but with a variation. 

Github with as a lone developer and with few files is not to difficult. You could even manage it from the browser and copying file back and forth! 

For some reason, my code gets rid of your tetra mesh, and create its own. (yes btw, if it is faster, don't bother generating a tet mesh, just work with triangles!)  For that, I call tetgen. Plugging to tet meshers how I want is not trivial, but that might be do-able in the future.

**Comment by otaolafranc** [comment]
Okis for the colors, thanks will test with different shades and for the white maybe Grey?
I need to check for github.
I regards to tet mesh, I suspected as i gave as input a tri mesh and it was Okey actually 🤣. But we'll talking about licenses from memory there are some license compatibility problems with tet Gen also quite old tool I imagine that newer tools might be more powerful (netgen and gmsh)
