### ISSUE TITLE
scaling issue between input and output mesh

### ISSUE THREAD

**Issue by otaolafranc** [fprotais/robustPolycube#4]
hello,
I am facing an scaling issue between the input and output meshes.
here is the inputand output mesh: 
[Archive.tar.gz](https://github.com/user-attachments/files/18255065/Archive.tar.gz)
the output mesh was obtained using: `../build/rb_fromscratch test.mesh 1. testOut.mesh`
thanks in advance and sorry for the number of issues hope to not bother too much
regards,
franco

**Comment by fprotais** [comment]
Hey there, I've implemented a scale-back mechanism. Let me know if it works for you (only for the fromscratch executable though). 
I should have streamlined the use of graphite as well. Let me know if everything works ok for you. 

It is good to have you helping you improve the thing :)

**Comment by otaolafranc** [comment]
hello francois, with the last update ./rb_fromscratch is failling;
```
../build/rb_fromscratch B0.mesh 1. b.mesh
../build/rb_fromscratch: error while loading shared libraries: libRB_libflagging.so: cannot open shared object file: No such file or directory

```

**Comment by fprotais** [comment]
Does it still do that if you: 
`rm -rf build`
And the re-do the installation process? Cmake may not have been updated correctly. (A clean build work on my machine, but there might be difference there)

**Comment by otaolafranc** [comment]
strange, i deleted the complete repo and clonned again when i had this error, but now it works my bad.

**Comment by otaolafranc** [comment]
> Hey there, I've implemented a scale-back mechanism. Let me know if it works for you (only for the fromscratch executable though). I should have streamlined the use of graphite as well. Let me know if everything works ok for you.
> 
> It is good to have you helping you improve the thing :)

is it possible for the 'classic' workflow to get the scaling factor from the log or something?
I am asking because I would like to use the repo with two different pipelines:
one that stops at end result of step 4. (ie., rb_generate_quantization)
and the other at thend of step 5. (ie., rb_fromscratch ) 
so for the fist pipeline i would require a scaling factor to scale it back
thanks

**Comment by fprotais** [comment]
If you want to avoid any issue, you can predict what my code will do: you can have a look at: 
https://github.com/fprotais/robustPolycube/blob/4f21b7394d10d0b86629ee34bef8516753c5a94f/lib/deformation/tools.cpp#L278
that does the scaling, and do a similar step before/after sending the model to my code. This way, you would not have to fight against the wrong scaling. 

On my side, the scaling is to used to tune numerical parameters for my optimizations.

**Comment by otaolafranc** [comment]
so correct me if I am wrong, but the scale factor would be this:
https://github.com/fprotais/robustPolycube/blob/4f21b7394d10d0b86629ee34bef8516753c5a94f/lib/deformation/tools.cpp#L279
(well 1/scale for you to _normalize_)

**Comment by fprotais** [comment]
Yes, but then the model is centered in 0 as well. You have the scale_back(...) in the associated .h file
